### ISSUE TITLE
mainにPRがマージされた時にリリースノートを作成する

### ISSUE THREAD

**Issue by fo-ji** [fo-ji/forwards#1223]
- https://zenn.dev/rehabforjapan/articles/github-actions-release-note
- [Dependabot が作成するプルリクエストについて]
リリースノート自動作成時にもコミット履歴が反映されるようするため、コミットメッセージの接頭辞はfeatから始まるようにします。
プルリクエスト作成時にはラベルも自動で付与するように設定しています。xxxxx dependencies, feat, minor release
パッケージのバージョンによって影響が発生するケースがあるため、miror release扱いにしています。
dependabot.ymlの定義は下記のようにしています。
```
  commit-message:
    # Prefix all commit messages with "feat: "
    prefix: 'feat'
  target-branch: 'dev'
  labels:
    - 'npm dependencies'
    - 'feat'
    - 'minor release'
  # Limit open pull requests to 10 at any time
  open-pull-requests-limit: 10
```
